target: AMA

# Default pathnames, change if needed
refs: refs
pair1: raw_reads/1
pair2: raw_reads/2
forward: adapters/forwardPrimers
rev: adapters/reversePrimers
out: out

# step2a_dada2.R
cutoff: 50 # cutoff for # of reads - remove samples that have less than this number of reads after sampling
seed: 100 # set the seed of R's random number generator

# haplotype_censoring.R
haplotype_length: 300 # length of the majority of haplotypes - (300 nucleotides for pfama1, 288 nucleotides for pfcsp)