# select whether you want to run haplotype calling or variant calling with this pipeline
# variant_calling: false

# Specify multiple targets to run in parallel, ie. target: ["AMA", "CSP"]
# check to see if it works w no variant calling or vice versa, and if a target is in both lists
# target: ["PFMDR1", "PFCRT"]
# target: ["AMA", "CSP"]

haplotype_calling_targets: ["AMA", "CSP"]
variant_calling_targets: ["PFMDR1", "PFCRT"]

# Paths for input and output data
pair1: raw_reads/1
pair2: raw_reads/2
trim_filter_out: trim_filter_out

# Default pathnames, change if needed
refs: refs
forward: adapters/forwardPrimers
rev: adapters/reversePrimers
variant_table: raw_reads/tables/DR_annos.csv

# step4_trim_and_filter
truncQ_values: [2, 5, 10, 15, 20, 25] # values of truncQ to be used in the filterAndTrim function to find the optimal truncQ value

# step6_call_haplotypes.R
cutoff: 50 # cutoff for # of reads - remove samples that have less than this number of reads after sampling
seed: 100 # set the seed of R's random number generator

# step7_haplotype_censoring.R
read_depth: 250 # remove haplotypes that occur in less than this amount of the sample reads, ie. less than 250 of the sample reads
proportion: 0.03 # remove haplotypes that occur in less than this percentage of the sample reads, ie. occur in less than 3% of the sample reads
read_depth_ratio: 8 # for haplotypes that have 1 SNP difference, occur in the same sample, and have a greater than this amount times read depth difference between them within that sample, removed the haplotype with the lower read depth from that sample, ie. > 8 times read depth difference