name: haplotype_calling

channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  # - bcftools=1.3.1
  # - bwa=0.7.12
  # - graphviz=2.38.0
  - python=3.8.12
  # - samtools=1.3.1
  - snakemake=7.0.1
  # - pyyaml=3.11
  - fastqc=0.11.9
  - cutadapt=3.7
  - bbmap=38.18
  - bioconductor-dada2=1.20.0
  - r-base=4.1.2
  - r-biocmanager=1.30.16
  - r-readr=2.1.2
  - r-dplyr=1.0.7
  - r-tidyr=1.2.0
  - r-lubridate=1.8.0
  - r-data.table=1.14.2
  - clustalw=2.1
  - muscle=5.1
  - r-ape=5.6
  - r-sjmisc=2.8.9
#fastq
#cutadapt
#bbmap
#r base
#dada2
# conda env update -f /path