name: haplotype_calling

channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.8.12
  - snakemake=7.20.0
  - fastqc=0.11.9
  - cutadapt=4.1
  - bbmap=39.01
  - bioconductor-dada2=1.20.0
  - r-base=4.1.2
  - r-biocmanager=1.30.16
  - r-readr=2.1.2
  - r-dplyr=1.0.10
  - clustalw=2.1
  - muscle=5.1
  - r-ape=5.6
  - r-sjmisc=2.8.9
  - trimmomatic=0.38
  - bash=5.1.16
  - r-tidyverse=1.3.1
  - r-rlang=1.0.6
  - r-cli=3.6.0
  - r-vctrs=0.4.1
  - r-tidyselect=1.2.0