name: haplotype_calling

channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - python=3.8.12
  - snakemake=7.0.1
  - fastqc=0.11.9
  - cutadapt=3.7
  - bbmap=38.18
  - bioconductor-dada2=1.20.0
  - r-base=4.1.2
  - r-biocmanager=1.30.16
  - r-readr=2.1.2
  - r-dplyr=1.0.7
  - clustalw=2.1
  - muscle=5.1
  - r-ape=5.6
  - r-sjmisc=2.8.9
  - trimmomatic=0.38